packages:
  # All packages in the monorepo, including shared libraries, MFEs, and the shell.
  # The double-star glob ('**') ensures that nested packages like those in 'packages/mfes/*' are discovered.
  - 'packages/**'

  # All backend microservices.
  - 'services/*'
