/**
 * @file AiCodingChallenge.tsx
 * @description This file contains the implementation of the AI Coding Challenge feature.
 * It allows users to generate a coding challenge, write a solution, run it against test cases in a sandboxed environment,
 * and receive AI-powered feedback on their code.
 * @copyright James Burvel O'Callaghan III
 * @license Apache-2.0
 */

import React, { useState, useCallback, useEffect, useRef } from 'react';
import { generateJson, getSolutionFeedbackStream } from '../services/aiService';
import { Type } from '@google/genai';
import { BeakerIcon, SparklesIcon } from './icons';
import { LoadingSpinner, MarkdownRenderer } from './shared';

// JSDoc: These types would ideally live in a central `types.ts` file.

/**
 * @typedef {object} TestCase
 * @description Represents a single test case for a coding challenge.
 * @property {any[]} input - An array of arguments to be passed to the user's function.
 * @property {*} expected - The expected output for the given input.
 */
interface TestCase {
  input: any[];
  expected: any;
}

/**
 * @typedef {object} CodingChallenge
 * @description Represents the structured data for a coding challenge generated by the AI.
 * @property {string} title - The title of the challenge.
 * @property {string} description - A detailed description of the problem in Markdown format.
 * @property {string} functionStub - A boilerplate function stub for the user to start with.
 * @property {TestCase[]} testCases - An array of test cases to validate the user's solution.
 */
interface CodingChallenge {
  title: string;
  description: string;
  functionStub: string;
  testCases: TestCase[];
}

/**
 * @typedef {object} TestResult
 * @description Represents the result of running a single test case.
 * @augments TestCase
 * @property {*} output - The actual output from the user's function.
 * @property {boolean} passed - Whether the actual output matches the expected output.
 * @property {string | null} error - Any error message produced during execution.
 */
interface TestResult extends TestCase {
  output: any;
  passed: boolean;
  error: string | null;
}

/**
 * @component AiCodingChallenge
 * @description An interactive component for practicing coding skills. It generates a challenge,
 * provides a code editor, runs tests in a sandboxed web worker, and offers AI-powered feedback.
 * @performance Offloads code execution to a Web Worker to prevent blocking the main UI thread.
 * @security User-submitted code is executed within a Web Worker, providing a basic sandbox. However, for a production environment, a more robust sandboxing solution (like a secure iframe or a dedicated microservice) is recommended to mitigate all potential security risks.
 * @example <AiCodingChallenge />
 */
export const AiCodingChallenge: React.FC = () => {
  const [challenge, setChallenge] = useState<CodingChallenge | null>(null);
  const [userCode, setUserCode] = useState('');
  const [testResults, setTestResults] = useState<TestResult[]>([]);
  const [aiFeedback, setAiFeedback] = useState('');
  const [isLoadingChallenge, setIsLoadingChallenge] = useState(true);
  const [isTestingCode, setIsTestingCode] = useState(false);
  const [isGettingFeedback, setIsGettingFeedback] = useState(false);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState<'tests' | 'feedback'>('tests');

  const workerRef = useRef<Worker | null>(null);

  useEffect(() => {
    /**
     * @performance
     * The Web Worker script is created on component mount. This worker will handle the execution
     * of user-submitted code, isolating it from the main thread and providing a security sandbox.
     */
    const workerScript = `
      self.onmessage = function(e) {
        const { code, testCase } = e.data;
        try {
          // NOTE: Using 'new Function' is a security risk. In a production app, a more robust sandboxing library should be used.
          const userFunc = new Function('...args', code);
          const output = userFunc(...testCase.input);
          self.postMessage({ output: output, error: null });
        } catch (err) {
          self.postMessage({ output: null, error: err.message });
        }
      };
    `;
    const blob = new Blob([workerScript], { type: 'application/javascript' });
    workerRef.current = new Worker(URL.createObjectURL(blob));

    return () => {
      workerRef.current?.terminate();
    };
  }, []);

  /**
   * @function handleGenerateChallenge
   * @description Fetches a new coding challenge from the AI service and updates the component's state.
   * @param {string | null} [topic='general'] - An optional topic for the coding challenge.
   * @returns {Promise<void>}
   */
  const handleGenerateChallenge = useCallback(async (topic: string | null = 'general') => {
    setIsLoadingChallenge(true);
    setError('');
    setChallenge(null);
    setUserCode('');
    setTestResults([]);
    setAiFeedback('');

    try {
      const schema = {
        type: Type.OBJECT,
        properties: {
          title: { type: Type.STRING },
          description: { type: Type.STRING },
          functionStub: { type: Type.STRING },
          testCases: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                input: { type: Type.ARRAY, items: {} },
                expected: {},
              },
              required: ['input', 'expected'],
            },
          },
        },
        required: ['title', 'description', 'functionStub', 'testCases'],
      };

      const newChallenge = await generateJson<CodingChallenge>(
        `Generate a medium-difficulty coding challenge about ${topic}. Include a title, a Markdown description, a JS function stub, and at least 3 test cases with diverse inputs (including edge cases).`,
        'You are an expert programming instructor creating coding challenges.',
        schema
      );

      setChallenge(newChallenge);
      setUserCode(newChallenge.functionStub);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate challenge.');
    } finally {
      setIsLoadingChallenge(false);
    }
  }, []);

  useEffect(() => {
    handleGenerateChallenge();
  }, [handleGenerateChallenge]);

  /**
   * @function handleRunTests
   * @description Executes the user's code against the challenge's test cases in a sandboxed Web Worker.
   * @returns {Promise<void>}
   */
  const handleRunTests = useCallback(async () => {
    if (!challenge || !workerRef.current) return;

    setIsTestingCode(true);
    setActiveTab('tests');
    setTestResults([]);

    const results: TestResult[] = [];
    for (const testCase of challenge.testCases) {
      const result = await new Promise<{ output: any; error: string | null }>((resolve) => {
        const onMessage = (e: MessageEvent) => {
          workerRef.current?.removeEventListener('message', onMessage);
          resolve(e.data);
        };
        workerRef.current?.addEventListener('message', onMessage);
        workerRef.current?.postMessage({ code: userCode, testCase });
      });

      // Simple deep equality check for arrays/objects
      const passed = JSON.stringify(result.output) === JSON.stringify(testCase.expected);
      results.push({ ...testCase, ...result, passed });
    }

    setTestResults(results);
    setIsTestingCode(false);
  }, [userCode, challenge]);

  /**
   * @function handleGetFeedback
   * @description Requests AI-powered feedback on the user's solution.
   * @returns {Promise<void>}
   */
  const handleGetFeedback = useCallback(async () => {
    if (!challenge) return;
    setIsGettingFeedback(true);
    setActiveTab('feedback');
    setAiFeedback('');
    try {
      const prompt = `Please review my solution for the following coding challenge.\n\n**Challenge:**\n${challenge.description}\n\n**My Solution:**\n\`\`\`javascript\n${userCode}\n\`\`\`\n\nProvide feedback on correctness, efficiency, and code style.`;
      const stream = getSolutionFeedbackStream(challenge.description, userCode);
      let fullResponse = '';
      for await (const chunk of stream) {
        fullResponse += chunk;
        setAiFeedback(fullResponse);
      }
    } catch (err) {
      setAiFeedback(`Error getting feedback: ${err instanceof Error ? err.message : 'Unknown error'}`);
    } finally {
      setIsGettingFeedback(false);
    }
  }, [userCode, challenge]);

  if (isLoadingChallenge) {
    return <div className="h-full flex items-center justify-center"><LoadingSpinner /></div>;
  }

  if (error) {
    return <div className="h-full flex items-center justify-center text-red-500 p-4">Error: {error}</div>;
  }

  return (
    <div className="h-full flex flex-col p-4 sm:p-6 lg:p-8 text-text-primary">
      <header className="mb-6 flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold flex items-center">
            <BeakerIcon />
            <span className="ml-3">{challenge?.title || 'AI Coding Challenge'}</span>
          </h1>
          <p className="text-text-secondary mt-1">Generate a unique coding problem to test your skills.</p>
        </div>
        <button onClick={() => handleGenerateChallenge()} className="btn-primary flex items-center justify-center px-6 py-2">Generate New</button>
      </header>
      <div className="flex-grow grid grid-cols-1 lg:grid-cols-2 gap-6 min-h-0">
        <div className="flex flex-col bg-surface border border-border rounded-lg overflow-y-auto p-4">
          <MarkdownRenderer content={challenge?.description || ''} />
        </div>
        <div className="flex flex-col gap-4 min-h-0">
          <div className="flex-grow flex flex-col min-h-0">
            <label className="text-sm font-medium mb-2 text-text-secondary">Your Solution</label>
            <textarea
              value={userCode}
              onChange={(e) => setUserCode(e.target.value)}
              className="flex-grow p-4 bg-background border border-border rounded-md resize-none font-mono text-sm focus:ring-2 focus:ring-primary focus:outline-none"
              spellCheck="false"
            />
          </div>
          <div className="flex gap-2">
            <button onClick={handleRunTests} disabled={isTestingCode} className="btn-primary flex-1 py-2 flex items-center justify-center">{isTestingCode ? <LoadingSpinner /> : 'Run Tests'}</button>
            <button onClick={handleGetFeedback} disabled={isGettingFeedback} className="bg-purple-600 text-white font-bold rounded-md hover:opacity-90 transition-all disabled:opacity-50 shadow-md flex-1 py-2 flex items-center justify-center gap-2">{isGettingFeedback ? <LoadingSpinner /> : <><SparklesIcon /> AI Feedback</>}</button>
          </div>
          <div className="flex-grow flex flex-col bg-surface border border-border rounded-lg overflow-hidden min-h-[200px]">
            <div className="flex border-b border-border">
              <button onClick={() => setActiveTab('tests')} className={`px-4 py-2 text-sm ${activeTab === 'tests' ? 'bg-background text-primary font-semibold' : 'text-text-secondary'}`}>Test Results</button>
              <button onClick={() => setActiveTab('feedback')} className={`px-4 py-2 text-sm ${activeTab === 'feedback' ? 'bg-background text-primary font-semibold' : 'text-text-secondary'}`}>AI Feedback</button>
            </div>
            <div className="p-4 overflow-y-auto">
              {activeTab === 'tests' && (
                isTestingCode ? <div className="flex justify-center"><LoadingSpinner /></div> : (
                  <div className="space-y-2 text-sm">
                    {testResults.map((result, i) => (
                      <div key={i} className={`p-2 rounded border ${result.passed ? 'border-green-500/30 bg-green-500/10' : 'border-red-500/30 bg-red-500/10'}`}>
                        <p className="font-bold flex items-center gap-2">{result.passed ? 'âœ…' : 'â❌'} Test Case #{i + 1}</p>
                        <p className="font-mono text-xs">Input: {JSON.stringify(result.input)}</p>
                        <p className="font-mono text-xs">Expected: {JSON.stringify(result.expected)}</p>
                        {result.error ? <p className="font-mono text-xs text-red-500">Error: {result.error}</p> : <p className="font-mono text-xs">Output: {JSON.stringify(result.output)}</p>}
                      </div>
                    ))}
                  </div>
                )
              )}
              {activeTab === 'feedback' && (
                isGettingFeedback ? <div className="flex justify-center"><LoadingSpinner /></div> : <MarkdownRenderer content={aiFeedback} />
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
