name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "autocommit-all" ]
  pull_request:
    branches: [ "autocommit-all" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Lint code for style and documentation standards
      run: pnpm run lint

    - name: Typecheck code
      run: pnpm run typecheck

    - name: Build application for production
      run: pnpm run build

    - name: Generate documentation portal
      run: pnpm run docs:generate

    - name: Format code
      run: pnpm run format
